# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/inventory.proto\x12\tinventory\"\x07\n\x05\x45mpty\"V\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\r\n\x05stock\x18\x05 \x01(\x05\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"X\n\x0fProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x07product\x18\x03 \x01(\x0b\x32\x12.inventory.Product\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd5\x02\n\x10InventoryService\x12<\n\nAddProduct\x12\x12.inventory.Product\x1a\x1a.inventory.ProductResponse\x12\x43\n\nGetProduct\x12\x19.inventory.ProductRequest\x1a\x1a.inventory.ProductResponse\x12?\n\rUpdateProduct\x12\x12.inventory.Product\x1a\x1a.inventory.ProductResponse\x12\x45\n\rDeleteProduct\x12\x19.inventory.ProductRequest\x1a\x19.inventory.DeleteResponse\x12\x36\n\x0cListProducts\x12\x10.inventory.Empty\x1a\x12.inventory.Product0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_PRODUCT']._serialized_start=45
  _globals['_PRODUCT']._serialized_end=131
  _globals['_PRODUCTREQUEST']._serialized_start=133
  _globals['_PRODUCTREQUEST']._serialized_end=161
  _globals['_PRODUCTRESPONSE']._serialized_start=163
  _globals['_PRODUCTRESPONSE']._serialized_end=251
  _globals['_DELETERESPONSE']._serialized_start=253
  _globals['_DELETERESPONSE']._serialized_end=303
  _globals['_INVENTORYSERVICE']._serialized_start=306
  _globals['_INVENTORYSERVICE']._serialized_end=647
# @@protoc_insertion_point(module_scope)
