# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\x1a\x1cgoogle/api/annotations.proto\"\x07\n\x05\x45mpty\"V\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\r\n\x05stock\x18\x05 \x01(\x05\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"X\n\x0fProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x07product\x18\x03 \x01(\x0b\x32\x12.inventory.Product\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd3\x03\n\x10InventoryService\x12U\n\nAddProduct\x12\x12.inventory.Product\x1a\x1a.inventory.ProductResponse\"\x17\x82\xd3\xe4\x93\x02\x11\"\x0c/v1/productsB\x01*\x12^\n\nGetProduct\x12\x19.inventory.ProductRequest\x1a\x1a.inventory.ProductResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/products/{id}\x12X\n\rUpdateProduct\x12\x12.inventory.Product\x1a\x1a.inventory.ProductResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x1a\x0c/v1/productsB\x01*\x12`\n\rDeleteProduct\x12\x19.inventory.ProductRequest\x1a\x19.inventory.DeleteResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/products/{id}\x12L\n\x0cListProducts\x12\x10.inventory.Empty\x1a\x12.inventory.Product\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/v1/products0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVENTORYSERVICE'].methods_by_name['AddProduct']._loaded_options = None
  _globals['_INVENTORYSERVICE'].methods_by_name['AddProduct']._serialized_options = b'\202\323\344\223\002\021\"\014/v1/productsB\001*'
  _globals['_INVENTORYSERVICE'].methods_by_name['GetProduct']._loaded_options = None
  _globals['_INVENTORYSERVICE'].methods_by_name['GetProduct']._serialized_options = b'\202\323\344\223\002\023\022\021/v1/products/{id}'
  _globals['_INVENTORYSERVICE'].methods_by_name['UpdateProduct']._loaded_options = None
  _globals['_INVENTORYSERVICE'].methods_by_name['UpdateProduct']._serialized_options = b'\202\323\344\223\002\021\032\014/v1/productsB\001*'
  _globals['_INVENTORYSERVICE'].methods_by_name['DeleteProduct']._loaded_options = None
  _globals['_INVENTORYSERVICE'].methods_by_name['DeleteProduct']._serialized_options = b'\202\323\344\223\002\023*\021/v1/products/{id}'
  _globals['_INVENTORYSERVICE'].methods_by_name['ListProducts']._loaded_options = None
  _globals['_INVENTORYSERVICE'].methods_by_name['ListProducts']._serialized_options = b'\202\323\344\223\002\016\022\014/v1/products'
  _globals['_EMPTY']._serialized_start=60
  _globals['_EMPTY']._serialized_end=67
  _globals['_PRODUCT']._serialized_start=69
  _globals['_PRODUCT']._serialized_end=155
  _globals['_PRODUCTREQUEST']._serialized_start=157
  _globals['_PRODUCTREQUEST']._serialized_end=185
  _globals['_PRODUCTRESPONSE']._serialized_start=187
  _globals['_PRODUCTRESPONSE']._serialized_end=275
  _globals['_DELETERESPONSE']._serialized_start=277
  _globals['_DELETERESPONSE']._serialized_end=327
  _globals['_INVENTORYSERVICE']._serialized_start=330
  _globals['_INVENTORYSERVICE']._serialized_end=797
# @@protoc_insertion_point(module_scope)
